### PR TITLE
feat: Add reCAPTCHA v3 script and enable it for login form

### PR DESCRIPTION
**Pull request by mohitahlawat2001**
This commit adds the reCAPTCHA v3 script to the root HTML file and enables it for the login form. The reCAPTCHA script is loaded from "https://www.google.com/recaptcha/api.js" asynchronously. Additionally, a callback function "onSubmit" is added to handle the reCAPTCHA token and submit the login form. The submit button is modified to be a reCAPTCHA v3-enabled button with the necessary data attributes. for issue #3

### CODE REVIEW

**Comment by harshmangalam** [comment]
Thanks @mohitahlawat2001. Have you added any siteKey env variable for this feature ?

**Comment by mohitahlawat2001** [comment]
please hacktoberfest-accepted , hacktoberfest label , siteKey can directly used in html , didnt use env for this , sitekey is not scret

**Comment by harshmangalam** [comment]
There is some issues with this PR
- Not able to submit login form
- Uncaught SyntaxError: Unexpected token '&'Understand this error
2recaptcha__en.js:173

**Comment by harshmangalam** [comment]
Can you please create a new PR for the above fix and test from your side  ?

**Comment by mohitahlawat2001** [comment]
can you share screenshot for this error

**Comment by harshmangalam** [comment]
Please take the latest pull auth error resolved

**Comment by mohitahlawat2001** [comment]
Can you label this as invalid, please

**Comment by harshmangalam** [comment]
Okay

**Pull request merged**
