### PR TITLE
feat:Help page

### PR DESCRIPTION
**Pull request by Pavankumar07s**
#21 I have not used Router and any useMemo hooks to optimize the react page .
If you like my countribution then give a thumsUp.😊

### CODE REVIEW

**Comment by Pavankumar07s** [comment]
hey @harshmangalam have a look on help page.

**Comment by harshmangalam** [comment]
@Pavankumar07s this app is using Qwik not React but the routing is similer to Next.js file based router do not need any external router libraries.

For more info please take a look to the existing file structure of application.

**Comment by Pavankumar07s** [comment]
Alright @harshmangalam changing the code.

**Comment by harshmangalam** [comment]
I have already mentioned the path where you need to add this code.

**Comment by Pavankumar07s** [comment]
@harshmangalam  i have read the documentation and this time i have used lazy loading also.

**Comment by harshmangalam** [comment]
Please do not delete .env.example

**Comment by harshmangalam** [comment]
Also its not `public` its inside `src/routes/(public)/help`. Please follow qwikcity docs for routing.

**Comment by harshmangalam** [comment]
Please use Qwik UI component library for Card.

**Comment by Pavankumar07s** [comment]
Alright @harshmangalam I will do it after my exams, please don't merge it but can you just accept my PR under Review approved.

**Comment by harshmangalam** [comment]
Hi @Pavankumar07s  ,

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like ig,linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Comment by Pavankumar07s** [comment]
@harshmangalam Thankyou ✨👍

**Pull request merged**
