### PR TITLE
fixed zod issues

### PR DESCRIPTION
**Pull request by hashnj**
The ZOD error is now fixed on signup page

### CODE REVIEW

**Comment by harshmangalam** [comment]
Thanks @hashnj . Can you please change base branch to dev ?

**Comment by hashnj** [comment]
done :)

**Comment by harshmangalam** [comment]
There is one issues here i am seeing lock file changes that do not have to do anything withn this issues can you please create new PR by remove lock file chaanges.

**Comment by hashnj** [comment]
sure thing

**Pull request merged**
