### PR TITLE
issue_68: help route ui update

### PR DESCRIPTION
**Pull request by SureshPradhana**
#68 
Updated /help page with card design similar to https://help.meetup.com/hc/en-us

### CODE REVIEW

**Comment by harshmangalam** [comment]
@SureshPradhana  added a review comment

**Comment by SureshPradhana** [comment]
@harshmangalam, I can't seem to see the review comment. Could you please check if it was added correctly?

**Comment by harshmangalam** [comment]
Can you please remove vite.config.ts.timestamp-1728791759742-6602f7cc36452.mjs file.

**Comment by SureshPradhana** [comment]
@harshmangalam updated

**Review by harshmangalam — APPROVED** [review]

**Comment by harshmangalam** [comment]
Thanks

**Comment by harshmangalam** [comment]
Hi @SureshPradhana   ,

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Pull request merged**
