### PR TITLE
feat:added both create-group ,create event and linked to given path

### PR DESCRIPTION
**Pull request by Pavankumar07s**
i have created both the parts of create event and create group and also applied same new separator.

### CODE REVIEW

**Review by harshmangalam — APPROVED** [review]

**Comment by harshmangalam** [comment]
Thanks @Pavankumar07s

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam thankyou for accepting my pr ,please give me hacktoberfest-accept badge😊

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam , could you please add the 'hacktoberfest-accepted' label to my pull request? I would really appreciate it. Thanks a lot!

**Comment by harshmangalam** [comment]
That required in PR  not in issues . Anyway done

**Comment by Pavankumar07s** [comment]
Thankyou @harshmangalam , sorry for confusion.

**Pull request merged**
