### PR TITLE
refactor:location label font-bold

### PR DESCRIPTION
**Pull request by tharikashree**

### CODE REVIEW

**Comment by tharikashree** [comment]
@harshmangalam 
Hey kindly review and merge the pr 
if any changes needed lmk

**Comment by harshmangalam** [comment]
Thanks @tharikashree for your contributions

**Comment by harshmangalam** [comment]
Hi @tharikashree ,

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like ig,linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Comment by tharikashree** [comment]
@harshmangalam 
Thank you for giving me the chance to contribute 
Very happy to help
This is my linkedin handle 
[LinkedIn](https://www.linkedin.com/in/tharika-shree-r-9a6912253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)

**Pull request merged**
