### PR TITLE
Logo updated

### PR DESCRIPTION
**Pull request by Srijan25**
image
does it look good now? please add tag if merging because last one got rejected

### CODE REVIEW

**Comment by harshmangalam** [comment]
Can you please resolve the conflict ?

**Comment by Srijan25** [comment]
resolved

**Comment by harshmangalam** [comment]
Hi @Srijan25 ,

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like ig,linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Comment by Srijan25** [comment]
thankyou so much. i am glad that you liked my work and i also learned so many things .
Here is my LinkedIn - https://www.linkedin.com/in/srijan-kumar-sah-1a276417b/
Insta- @srijan__2002

**Pull request merged**
